apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: mayastor
spec:
  version: {{ .TagName }}
  homepage: https://openebs.io/docs/
  shortDescription: Provides commands for OpenEBS Mayastor.
  description: |
    This plugin allows you to manage Mayastor volumes and upgrades.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/openebs/mayastor-extensions/releases/download/{{ .TagName }}/kubectl-mayastor-x86_64-apple-darwin.tar.gz" .TagName }}
    bin: kubectl-mayastor
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/openebs/mayastor-extensions/releases/download/{{ .TagName }}/kubectl-mayastor-aarch64-apple-darwin.tar.gz" .TagName }}
    bin: kubectl-mayastor
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/openebs/mayastor-extensions/releases/download/{{ .TagName }}/kubectl-mayastor-x86_64-linux-musl.tar.gz" .TagName }}
    bin: kubectl-mayastor
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/openebs/mayastor-extensions/releases/download/{{ .TagName }}/kubectl-mayastor-aarch64-linux-musl.tar.gz" .TagName }}
    bin: kubectl-mayastor
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/openebs/mayastor-extensions/releases/download/{{ .TagName }}/kubectl-mayastor-x86_64-windows-gnu.tar.gz" .TagName }}
    bin: kubectl-mayastor.exe
